version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "SHA256:iTODn8kc0CdATdssV6SG1hgMht0Xdgb3jy3/9+Ep7Ek"
      - run: git reset --hard
      - run: git pull
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - run: scp -r kim-larocca/* root@198.211.112.212:/var/www/kim-larocca/
workflows:
  build-and-test:
    jobs:
      - build-and-test
