version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b7:7b:56:37:97:40:5b:f9:76:71:14:5f:bb:39:8e:df"
      - run: git reset --hard
      - run: git pull
      - run: npm install
      - run: npm run lint --fix
      - run: npm run build
      - run: scp -r -o StrictHostKeyChecking=no dist/* root@198.211.112.212:/var/www/kim-larocca/dist/
workflows:
  build:
    jobs:
      - build
