version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "MD5:b7:7b:56:37:97:40:5b:f9:76:71:14:5f:bb:39:8e:df"
            - "53:e9:1a:71:cf:11:fd:ac:21:d2:b9:fb:dd:33:0d:b9"
      - run: git reset --hard
      - run: git pull
      - run: scp -r -o StrictHostKeyChecking=no /* root@198.211.112.212:/var/www/kim-larocca/
workflows:
  build:
    jobs:
      - build
